# This is not a formal BNF spec

<line> ::= <statement>

<statement> ::= <source> <unary_chain>;

<source> ::= <variable_label> | <literal>

<unary_chain> ::= <unary_op> | <unary_op> <unary_chain>

<unary_invoke> ::= <unary_op> | <repeater> <unary_op>
<repeater> ::= {int}
<unary_op> ::= + | - | STDOUT | <variable_label>

<literal> ::= int, float, 'letter', "string"
<variable_label> ::= \$(a-z|A-Z|_)+

